<a href="https://colab.research.google.com/github/averma12/fastai-nlp-course/blob/master/Pytorch_Language_Model_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [0]:
b = a[:, :-1]

In [28]:
a[:,-1]

array([ 4,  8, 12])

In [0]:
text = """Manakamana doesn't answer any questions, yet makes its point: Nepal, like the rest of our planet, is a picturesque but far from peaceable kingdom."""

In [0]:
chars = tuple(set(text))

In [31]:
chars

('p',
 'k',
 '.',
 ',',
 'c',
 'm',
 'a',
 'o',
 'q',
 'i',
 'e',
 'g',
 'r',
 'f',
 'w',
 't',
 ' ',
 ':',
 'M',
 'h',
 'N',
 's',
 'y',
 'l',
 'b',
 'd',
 "'",
 'n',
 'u')

In [0]:
int2char = dict(enumerate(chars))

In [0]:
char2int = {ch: ii for ii, ch in int2char.items()}

In [0]:
encoded = np.array([char2int[ch] for ch in text])

In [35]:
len(encoded)

146

In [36]:
np.array([1,2,3]).flatten()

array([1, 2, 3])

In [37]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [0]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [39]:
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


In [0]:
bs = 10
seq_len = 16

In [0]:
batches = np.array([encoded[i*seq_len:(i+1)*seq_len] for i in range(bs)])

In [42]:
batches

array([array([18,  6, 27,  6,  1,  6,  5,  6, 27,  6, 16, 25,  7, 10, 21, 27]),
       array([26, 15, 16,  6, 27, 21, 14, 10, 12, 16,  6, 27, 22, 16,  8, 28]),
       array([10, 21, 15,  9,  7, 27, 21,  3, 16, 22, 10, 15, 16,  5,  6,  1]),
       array([10, 21, 16,  9, 15, 21, 16,  0,  7,  9, 27, 15, 17, 16, 20, 10]),
       array([ 0,  6, 23,  3, 16, 23,  9,  1, 10, 16, 15, 19, 10, 16, 12, 10]),
       array([21, 15, 16,  7, 13, 16,  7, 28, 12, 16,  0, 23,  6, 27, 10, 15]),
       array([ 3, 16,  9, 21, 16,  6, 16,  0,  9,  4, 15, 28, 12, 10, 21,  8]),
       array([28, 10, 16, 24, 28, 15, 16, 13,  6, 12, 16, 13, 12,  7,  5, 16]),
       array([ 0, 10,  6,  4, 10,  6, 24, 23, 10, 16,  1,  9, 27, 11, 25,  7]),
       array([5, 2])], dtype=object)

In [0]:
bptt = 4

In [0]:
import pandas as pd
from IPython.display import display,HTML

In [45]:
for k in range(seq_len//bptt):
    d_tokens = np.array([encoded[i*seq_len + k*bptt:i*seq_len + (k+1)*bptt] for i in range(bs)])
    df = pd.DataFrame(d_tokens)
    display(HTML(df.to_html(index=False,header=None)))
    

In [14]:
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

Training on GPU!


In [16]:
len(encoded)//160

0

In [0]:
encoded_trunc = encoded[:100]

In [0]:
encoded_trunc = encoded_trunc.reshape(10,-1)

In [24]:
encoded_trunc.shape[1]

10